### ISSUE TITLE
Proposal to keep the order keys in JSON object

### ISSUE THREAD

**Issue by harshavardhana** [bcicen/jstream#4]
I have a requirement to keep the order of JSON object keys as the input order. For this I propose to change the return value of object() (map[string]interface{}) to object() ([]KV) 

Let me know what you think..

**Comment by bcicen** [comment]
If you have a depth level set to that of the targeted object, or have enabled recursive emit (`Recursive()` on the decoder), then`Stream()` will emit the KVs in the order they are read.

**Comment by harshavardhana** [comment]
Yeah but I am not interested in depth, I am only interested in key and values line by line.

Because I may not know the depth of any arbitrary JSON. The problem is right now map looses order of keys even within an object.

So returning a slice of KVs is better than a map..let me send a PR for more clarity.

**Comment by harshavardhana** [comment]
PR sent here #5 let me know what you think

**Comment by harshavardhana** [comment]
Checking back to see if you were able to look at the PR #5

**Comment by bcicen** [comment]
Commented on PR #5 -- my point about configuring the decoder for your use case is that it doesn't require knowledge of depth; e.g using the below input:
```json
[
  {
    "bio": "Hello, I'm Roberto",
    "id": 0,
    "name": "Roberto",
    "hello": true
  },
  {
    "bio": "Hi I'm Charles",
    "id": 1,
    "name": "Charles",
    "hello": false
  }
]
```

and decoding with:
```go
package main

import (
	"fmt"
	"os"
	"github.com/bcicen/jstream"
)

func main() {
	f, _ := os.Open("input.json")
	decoder := jstream.NewDecoder(f, -1).EmitKV() // emit at all depths
	for mv := range decoder.Stream() {
		if kv, ok := mv.Value.(jstream.KV); ok {
			fmt.Printf("%v\n ", kv)
		}
	}
}
```

results in an already-ordered stream of `KV`s:
```
{bio Hello, I'm Roberto}
{id 0}
{name Roberto}
{hello true}
{bio Hi I'm Charles}
{id 1}
{name Charles}
{hello false}
```

**Comment by harshavardhana** [comment]
yeah but the problem is it loses information about the parents @bcicen we don't know `bio` is the parent or `id`

**Comment by harshavardhana** [comment]
Closing as merged .
